### ISSUE TITLE
Game's font is not displayed when running game on old devices

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#205]
When running game (both web version and mobile version) on some older device, we don't have our game's font displayed at all and font substitution (i.e. to _Times New Roman_ etc.) walks in.

Our initial research had revealed that this could potentially be caused by the fact that the source code references .woff2 font file only and does not reference .otf, .ttf and .woff files:

```css
@font-face {
    font-family: 'Lost Pixelized Font';
    src: url('lpf.woff2') format('woff2');
    font-style: normal;
    font-weight: normal;
    text-rendering: optimizeLegibility;
}
```

Old browsers doesn't recognize .woff2 fonts formats and must be pointed out to either .woff, .otf or .ttf:

```css
/* Webfont: Lost Pixelized Font-Regular */
@font-face {
    font-family: 'LostPixelizedFont';
    src: url('Lost Pixelized Font.woff2') format('woff2'), /* Safari, Android, iOS */
         url('Lost Pixelized Font.woff') format('woff'), /* Modern Browsers */
         url('Lost Pixelized Font.otf') format('opentype'), /* Modern Browsers */
         url('Lost Pixelized Font.ttf') format('truetype'); /* IE6-IE9 */
    font-style: normal;
    font-weight: normal;
    text-rendering: optimizeLegibility;
}
```

But, please, double check, if this is truly the cause of this bug.
